# Generated by Django 4.1.3 on 2023-03-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = []
